//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICreatePasswordService")]
    public interface ICreatePasswordService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreatePasswordService/GenerateStringPin", ReplyAction="http://tempuri.org/ICreatePasswordService/GenerateStringPinResponse")]
        System.Threading.Tasks.Task<string> GenerateStringPinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreatePasswordService/GenerateIntegerPin", ReplyAction="http://tempuri.org/ICreatePasswordService/GenerateIntegerPinResponse")]
        System.Threading.Tasks.Task<string> GenerateIntegerPinAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ICreatePasswordServiceChannel : ServiceReference1.ICreatePasswordService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CreatePasswordServiceClient : System.ServiceModel.ClientBase<ServiceReference1.ICreatePasswordService>, ServiceReference1.ICreatePasswordService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CreatePasswordServiceClient() : 
                base(CreatePasswordServiceClient.GetDefaultBinding(), CreatePasswordServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICreatePasswordService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreatePasswordServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CreatePasswordServiceClient.GetBindingForEndpoint(endpointConfiguration), CreatePasswordServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreatePasswordServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CreatePasswordServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreatePasswordServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CreatePasswordServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreatePasswordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GenerateStringPinAsync()
        {
            return base.Channel.GenerateStringPinAsync();
        }
        
        public System.Threading.Tasks.Task<string> GenerateIntegerPinAsync()
        {
            return base.Channel.GenerateIntegerPinAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICreatePasswordService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICreatePasswordService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50451/CreatePasswordService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CreatePasswordServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICreatePasswordService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CreatePasswordServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICreatePasswordService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICreatePasswordService,
        }
    }
}
